Fix require at the beginning
Exception: require that are only ran, if the file is called as a
stand-alone program for testing (e.g. ruby debRelease.rb), the requires
that are only needed for that are at the start of the "if program==file" block.