Errata need to have binary packages
Fixed an errata parser issue for Ubuntu. This happend with the USN
https://ubuntu.com/security/notices/USN-8779-2 which only fixed the
regression for Ubuntu PRO packages. The other releases are part of the
USN json and "archs" was set, too but it did not contain any "binaries"
blocks. Only the "source" attribute was given. So, it looks more like an
issue of the USN - or it was necessary to fix the regression for the
Ubuntu PRO customer super fast and they did not care about usual Ubuntu
distributions.

Finally, this crashed with:

[7481]: At USN-8779-2:
[7481]: bundler: failed to load command: errata_parser.rb (errata_parser.rb)
[7481]: /errata_parser/gen_errata.rb:298:in `get_versions': undefined method `each_value' for nil (NoMethodError)
[7481]:     hsh.each_value do |b|
[7481]:        ^^^^^^^^^^^
[7481]: #011from /errata_parser/gen_errata.rb:328:in `add_packages_ubuntu'
[7481]: #011from /errata_parser/gen_errata.rb:388:in `block (2 levels) in gen_ubuntu_errata'
[7481]: #011from /errata_parser/gen_errata.rb:383:in `each'
[7481]: #011from /errata_parser/gen_errata.rb:383:in `block in gen_ubuntu_errata'
[7481]: #011from /errata_parser/gen_errata.rb:372:in `each'
[7481]: #011from /errata_parser/gen_errata.rb:372:in `gen_ubuntu_errata'